// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kuJ2RrKXjzvkIiCU9MUatQrwy7grPHs',
    appId: '1:482042580776:web:6195c69fcfc05948c60a1d',
    messagingSenderId: '482042580776',
    projectId: 'mastiplay-31ca8',
    authDomain: 'mastiplay-31ca8.firebaseapp.com',
    databaseURL: 'https://mastiplay-31ca8-default-rtdb.firebaseio.com',
    storageBucket: 'mastiplay-31ca8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tPY6LVeKIHTUZvIyBoijMbRcUITQBQY',
    appId: '1:482042580776:android:53a225cb68729f40c60a1d',
    messagingSenderId: '482042580776',
    projectId: 'mastiplay-31ca8',
    databaseURL: 'https://mastiplay-31ca8-default-rtdb.firebaseio.com',
    storageBucket: 'mastiplay-31ca8.appspot.com',
  );
}
